name: library_management_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  image_picker: ^1.2.0
  http: ^1.5.0
  uuid: ^4.5.1
  intl: ^0.20.2
  provider: ^6.1.5+1
  syncfusion_flutter_charts: ^31.1.19
  widgetbook_annotation: ^3.7.0
  widgetbook: ^3.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  widgetbook_generator: ^3.7.0
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
