// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK-_M0sr7FOC3uyzLKW9DUDqaQHItxGj8',
    appId: '1:1096288765331:web:952056497451ae90f7d466',
    messagingSenderId: '1096288765331',
    projectId: 'librarymanagerment-711b0',
    authDomain: 'librarymanagerment-711b0.firebaseapp.com',
    storageBucket: 'librarymanagerment-711b0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK-_M0sr7FOC3uyzLKW9DUDqaQHItxGj8',
    appId: '1:1096288765331:android:952056497451ae90f7d466',
    messagingSenderId: '1096288765331',
    projectId: 'librarymanagerment-711b0',
    storageBucket: 'librarymanagerment-711b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyJW4iF4GnduQV6xE6goPokbMfFp_ZHEg',
    appId: '1:1096288765331:ios:0e109bc3a01e455ef7d466',
    messagingSenderId: '1096288765331',
    projectId: 'librarymanagerment-711b0',
    storageBucket: 'librarymanagerment-711b0.firebasestorage.app',
    iosBundleId: 'com.example.libraryManagementApp',
  );
}
